CREATE DATABASE CRYTO_APP
GO

USE CRYTO_APP
GO

/*TABLE AREA*/
--TABLE INCLUDES USER INFORMATION
CREATE TABLE TBL_USER
(
	ID INT IDENTITY PRIMARY KEY,
	NAME VARCHAR(255),
	EMAIL VARCHAR(255)
)
GO

--TABLE INCLUDES USER INFORMATION
CREATE TABLE TBL_USER_ASSET
(
	ID INT IDENTITY PRIMARY KEY,
	ID_USER INT FOREIGN KEY(ID_USER) REFERENCES TBL_USER,
	TOTAL_MONEY FLOAT
)
GO

--TABLE INCLUDES ACCOUNT INFORMATION
CREATE TABLE TBL_ACCOUNT
(
	ID INT IDENTITY PRIMARY KEY,
	ID_USER INT FOREIGN KEY(ID_USER) REFERENCES TBL_USER,
	USER_NAME VARCHAR(255),
	PASS_WORD VARCHAR(255),
)
GO

--TABLE INCLUDES COIN INFORMATION
CREATE TABLE TBL_COIN
(
	ID INT IDENTITY PRIMARY KEY,
	COIN_NAME VARCHAR(255),
	IMAGE VARCHAR(255),
	QUANTITY INT DEFAULT 10
)
GO

--TABLE INCLUDES USER INFORMATION
CREATE TABLE TBL_USER_ASSET_COIN
(
	ID INT IDENTITY PRIMARY KEY,
	ID_USER INT FOREIGN KEY(ID_USER) REFERENCES TBL_USER,
	ID_COIN INT FOREIGN KEY(ID_COIN) REFERENCES TBL_COIN,
	COIN_QUANTITY INT
)
GO

--TABLE INCLUDES TRADING INFORMATION
CREATE TABLE TBL_TRADING
(
	ID INT IDENTITY PRIMARY KEY,
	ID_USER_BUY INT FOREIGN KEY(ID_USER_BUY) REFERENCES TBL_USER,
	ID_USER_SELL INT FOREIGN KEY(ID_USER_SELL) REFERENCES TBL_USER,
	ID_COIN INT FOREIGN KEY(ID_COIN) REFERENCES TBL_COIN,
	COIN_QUANTITY_TRADING INT,
	PRICE FLOAT,
	TIME_TRADING DATETIME
)
GO

--TABLE INCLUDES TRADING-BUY INFORMATION
CREATE TABLE TBL_TRADING_BUY
(
	ID INT IDENTITY PRIMARY KEY,
	ID_USER_BUY INT FOREIGN KEY(ID_USER_BUY) REFERENCES TBL_USER,
	ID_TRADING INT FOREIGN KEY(ID_TRADING) REFERENCES TBL_TRADING,
	ID_COIN INT FOREIGN KEY(ID_COIN) REFERENCES TBL_COIN,
	COIN_QUANTITY_TRADING INT,
	PRICE FLOAT,
	TIME_TRADING DATETIME
)
GO

--TABLE INCLUDES TRADING-SELL INFORMATION
CREATE TABLE TBL_TRADING_SELL
(
	ID INT IDENTITY PRIMARY KEY,
	ID_USER_SELL INT FOREIGN KEY(ID_USER_SELL) REFERENCES TBL_USER,
	ID_TRADING INT FOREIGN KEY(ID_TRADING) REFERENCES TBL_TRADING,
	ID_COIN INT FOREIGN KEY(ID_COIN) REFERENCES TBL_COIN,
	COIN_QUANTITY_TRADING INT,
	PRICE FLOAT,
	TIME_TRADING DATETIME
)
GO

