CREATE DATABASE CRYTO_APP
GO

USE CRYTO_APP
GO

/*TABLE AREA*/
--TABLE INCLUDES ACCOUNT_USER INFORMATION
CREATE TABLE tbl_account_user
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255),
	EMAIL VARCHAR(255),
	PASS_WORD VARCHAR(255)
)
GO

--TABLE INCLUDES COIN INFORMATION
CREATE TABLE tbl_coin
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	COIN_NAME VARCHAR(255)
)
GO

--TABLE INCLUDES USER INFORMATION
CREATE TABLE tbl_user_asset
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_USER INT ,
	TOTAL_MONEY FLOAT DEFAULT 0,
    FOREIGN KEY(ID_USER) REFERENCES tbl_account_user(ID)
)

GO

--TABLE INCLUDES USER INFORMATION
CREATE TABLE tbl_user_asset_coin
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_USER INT FOREIGN KEY(ID_USER) REFERENCES TBL_USER,
	ID_COIN INT FOREIGN KEY(ID_COIN) REFERENCES TBL_COIN,
	COIN_QUANTITY INT,
	COIN_VALUE FLOAT
)
GO

--TABLE INCLUDES TRADING INFORMATION
CREATE TABLE tbl_trading
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_TRADING_SELL_BUY INT,
	ID_USER_TRADING INT,
	TRADING_TYPE VARCHAR(255),
	ID_COIN INT,
	COIN_QUANTITY_TRADING INT,
	PRICE FLOAT,
	TIME_TRADING DATETIME,
	STATUS VARCHAR(255) DEFAULT 'PENDING',
	FOREIGN KEY(ID_USER_TRADING) REFERENCES tbl_user_asset(ID)
)
GO

--TABLE INCLUDES TRADING-BUY INFORMATION
CREATE TABLE tbl_trading_buy
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_USER_BUY INT ,
	ID_COIN INT ,
	COIN_QUANTITY_TRADING INT,
	PRICE FLOAT,
	TIME_TRADING DATETIME,
	STATUS VARCHAR(255) DEFAULT 'PENDING',
    FOREIGN KEY(ID_USER_BUY) REFERENCES tbl_user_asset(ID),
    FOREIGN KEY(ID_COIN) REFERENCES tbl_coin(ID)
)
GO

--TABLE INCLUDES TRADING-SELL INFORMATION
CREATE TABLE tbl_trading_sell
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_USER_SELL INT ,
	ID_COIN INT ,
	COIN_QUANTITY_TRADING INT,
	PRICE FLOAT,
	TIME_TRADING DATETIME,
	STATUS VARCHAR(255) DEFAULT 'PENDING',
    FOREIGN KEY(ID_USER_SELL) REFERENCES tbl_account_user(ID),
    FOREIGN KEY(ID_COIN) REFERENCES tbl_coin(ID)
)
GO

--TRIGGER ON tbl_trading_sell
BEGIN

	INSERT INTO tbl_trading(ID_TRADING_SELL_BUY,ID_USER_TRADING,TRADING_TYPE,ID_COIN,COIN_QUANTITY_TRADING,PRICE,TIME_TRADING) 
	VALUES(NEW.ID, NEW.ID_USER_SELL, 'SELL', NEW.ID_COIN, NEW.COIN_QUANTITY_TRADING, NEW.PRICE, NEW.TIME_TRADING);

END


--TRIGGER ON tbl_trading_sell
BEGIN

	INSERT INTO tbl_trading(ID_TRADING_SELL_BUY,ID_USER_TRADING,TRADING_TYPE,ID_COIN,COIN_QUANTITY_TRADING,PRICE,TIME_TRADING) 
	VALUES(NEW.ID, NEW.ID_USER_BUY, 'BUY', NEW.ID_COIN, NEW.COIN_QUANTITY_TRADING, NEW.PRICE, NEW.TIME_TRADING);

END
------------------------------------------------------------------------

/*TBL_USER_ASSET*/
-- Deposit money
-- Withdraw money
-- Buy and sell function

/*TBL_COIN*/
-- Adding new coin
-- Removing coin BTC ETH 

/*TBL_USER_ASSET_COIN*/
-- Save coin asset
-- Save coin value
-- Calculate coin value

/*TBL_TRADING*/
--Save trading information
--Show data in diagram
--Update tbl_user_asset and tbl_user_asset_coin

/*TBL_TRADING_SELL/BUY*/
-- Show history
