CREATE DATABASE CRYTO_APP
GO

USE CRYTO_APP
GO

/*TABLE AREA*/
--TABLE INCLUDES ACCOUNT_USER INFORMATION
CREATE TABLE tbl_account_user
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255),
	EMAIL VARCHAR(255),
	PASS_WORD VARCHAR(255)
)
GO

--TABLE INCLUDES COIN INFORMATION
CREATE TABLE tbl_coin
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	COIN_NAME VARCHAR(255)
)
GO

--TABLE INCLUDES USER INFORMATION
CREATE TABLE tbl_user_asset
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_USER INT ,
	TOTAL_MONEY FLOAT DEFAULT 0,
    FOREIGN KEY(ID_USER) REFERENCES tbl_account_user(ID)
)

GO

--TABLE INCLUDES USER INFORMATION
CREATE TABLE tbl_user_asset_coin
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_USER INT FOREIGN KEY(ID_USER) REFERENCES TBL_USER,
	ID_COIN INT FOREIGN KEY(ID_COIN) REFERENCES TBL_COIN,
	COIN_QUANTITY INT,
	COIN_VALUE FLOAT
)
GO

--TABLE INCLUDES TRADING INFORMATION
CREATE TABLE TBL_TRADING
(
	ID INT IDENTITY PRIMARY KEY,
	ID_USER_BUY INT FOREIGN KEY(ID_USER_BUY) REFERENCES TBL_USER,
	ID_USER_SELL INT FOREIGN KEY(ID_USER_SELL) REFERENCES TBL_USER,
	ID_COIN INT FOREIGN KEY(ID_COIN) REFERENCES TBL_COIN,
	COIN_QUANTITY_TRADING INT,
	PRICE FLOAT,
	TIME_TRADING DATETIME
)
GO

--TABLE INCLUDES TRADING-BUY INFORMATION
CREATE TABLE TBL_TRADING_BUY
(
	ID INT IDENTITY PRIMARY KEY,
	ID_USER_BUY INT FOREIGN KEY(ID_USER_BUY) REFERENCES TBL_USER,
	ID_TRADING INT FOREIGN KEY(ID_TRADING) REFERENCES TBL_TRADING,
	ID_COIN INT FOREIGN KEY(ID_COIN) REFERENCES TBL_COIN,
	COIN_QUANTITY_TRADING INT,
	PRICE FLOAT,
	TIME_TRADING DATETIME
)
GO

--TABLE INCLUDES TRADING-SELL INFORMATION
CREATE TABLE TBL_TRADING_SELL
(
	ID INT IDENTITY PRIMARY KEY,
	ID_USER_SELL INT FOREIGN KEY(ID_USER_SELL) REFERENCES TBL_USER,
	ID_TRADING INT FOREIGN KEY(ID_TRADING) REFERENCES TBL_TRADING,
	ID_COIN INT FOREIGN KEY(ID_COIN) REFERENCES TBL_COIN,
	COIN_QUANTITY_TRADING INT,
	PRICE FLOAT,
	TIME_TRADING DATETIME
)
GO

/*TBL_USER*/

-- Add New User Function
INSERT INTO TBL_USER(NAME, EMAIL) VALUES('${Name_Value}','${Email_Value}')
-- Note: Name_Value and Email_Value are user's inputs

------------------------------------------------------------------------

/*TBL_ACCOUNT*/

-- Add New Account Function
INSERT INTO TBL_ACCOUNT(USER_NAME, PASS_WORD) VALUES('${User_Name_Value}','${Pass_Word_Value}')
-- Note: User_Name_Value and Pass_Word_Value are user's inputs

-- New Password
UPDATE TBL_ACCOUNT SET PASS_WORD = ${New_Pass_Word_Value} WHERE USER_NAME = ${User_Name_Value}
-- Note: User_Name_Value and New_Pass_Word_Value are user's inputs

------------------------------------------------------------------------

/*TBL_USER_ASSET*/
-- Deposit money
-- Withdraw money
-- Buy and sell function

/*TBL_COIN*/
-- Adding new coin
-- Removing coin BTC ETH 

/*TBL_USER_ASSET_COIN*/
-- Save coin asset
-- Save coin value
-- Calculate coin value

/*TBL_TRADING*/
--Save trading information
--Show data in diagram
--Update tbl_user_asset and tbl_user_asset_coin

/*TBL_TRADING_SELL/BUY*/
-- Show history
